"""Reusable station-name phrase lists for speech input customization.

Station names are sourced from the iRail stations API:
https://api.irail.be/stations/?format=json&lang=<language>

Each language list includes both localized station names and the iRail
``standardname`` aliases, deduplicated in source order.
"""

from __future__ import annotations

from typing import Final

phrase_list_en: list[str] = [
    "'s Hertogenbosch",
    "Aachen Hbf",
    "Aachen West",
    "Aalst",
    "Aalst-Kerrebroek",
    "Aalter",
    "Aarschot",
    "Aarsele",
    "Acren",
    "Agde",
    "Aime-la-Plagne",
    "Aiseau",
    "Aix-en-Provence TGV",
    "Albertville",
    "Alken",
    "Almere Buiten",
    "Almere Centrum",
    "Amay",
    "Ampsin",
    "Amsterdam CS",
    "Amsterdam Centraal",
    "Amsterdam Zuid",
    "Andenne",
    "Anderlecht",
    "Angleur",
    "Annappes",
    "Ans",
    "Anseremme",
    "Antibes",
    "Antoing",
    "Antwerp-Berchem",
    "Antwerpen-Berchem",
    "Antwerp-Central",
    "Antwerpen-Centraal",
    "Antwerp-East",
    "Antwerpen-Oost",
    "Antwerp-Haven",
    "Antwerpen-Haven",
    "Antwerp-Linkeroever",
    "Antwerpen-Linkeroever",
    "Antwerp-Luchtbal",
    "Antwerpen-Luchtbal",
    "Antwerp-Noorderdokken",
    "Antwerpen-Noorderdokken",
    "Antwerp-South",
    "Antwerpen-Zuid",
    "Antwerpen-Dam",
    "Anzegem",
    "Appelterre",
    "Arcaden",
    "Arcaden/Arcades",
    "Archennes",
    "Arlon",
    "Arras",
    "Ascq",
    "Asse",
    "Assesse",
    "Ath",
    "Athus",
    "Athus-Frontiere",
    "Aubange",
    "Aubange-Frontiere-Luxembourg",
    "Aulnoye-Aymeries",
    "Auvelais",
    "Avignon TGV",
    "Aye",
    "Aywaille",
    "Aéroport Charles-de-Gaulle TGV",
    "Baasrode-Zuid",
    "Baisieux",
    "Balegem-Dorp",
    "Balegem-Zuid",
    "Balen",
    "Bambrugge",
    "Barvaux",
    "Bas-Oha",
    "Bascharage-Sanem",
    "Basel",
    "Basse-Wavre",
    "Bastogne-Nord",
    "Bastogne-Sud",
    "Beauraing",
    "Beernem",
    "Beersel",
    "Beervelde",
    "Begijnendijk",
    "Beignée",
    "Bellem",
    "Belsele",
    "Beringen",
    "Berlaar",
    "Berlin HBF",
    "Berlin Lichtenberg",
    "Berlin Ostbahnhof",
    "Bertrange Strassen",
    "Bertrix",
    "Berzée",
    "Beuzet",
    "Beveren",
    "Beverlo",
    "Bierges-Walibi",
    "Bierset-Awans",
    "Bilzen",
    "Binche",
    "Bissegem",
    "Blandain-Frontiere",
    "Blankenberge",
    "Blanmont",
    "Blaton",
    "Bleret",
    "Bockstael",
    "Boechout",
    "Bokrijk",
    "Bomal",
    "Bonn-Beuel",
    "Booischot",
    "Boom",
    "Boondaal/Boondael",
    "Boortmeerbeek",
    "Bordeaux Saint Jean",
    "Bordet",
    "Bornem",
    "Bosvoorde/Boitsfort",
    "Bourg-Saint-Maurice",
    "Boussu",
    "Bouwel",
    "Bracquegnies",
    "Braine-l'Alleud",
    "Braine-le-Comte",
    "Breda",
    "Bressoux",
    "Brugelette",
    "Brugge",
    "Brugge-Sint-Pieters",
    "Brussels Airport - Zaventem",
    "Brussels-Central",
    "Brussel-Centraal/Bruxelles-Central",
    "Brussels-Chapelle/Brussels-Kapellekerk",
    "Brussel-Kapellekerk/Bruxelles-Chapelle",
    "Brussels-Congres",
    "Brussel-Congres/Bruxelles-Congrès",
    "Brussels-Luxemburg/Brussels-Luxembourg",
    "Brussel-Luxemburg/Bruxelles-Luxembourg",
    "Brussels-North",
    "Brussel-Noord/Bruxelles-Nord",
    "Brussels-Schuman",
    "Brussel-Schuman/Bruxelles-Schuman",
    "Brussels-South/Brussels-Midi",
    "Brussel-Zuid/Bruxelles-Midi",
    "Brussels-West",
    "Brussel-West/Bruxelles-Ouest",
    "Buda",
    "Buggenhout",
    "Buizingen",
    "Burst",
    "Béziers",
    "Callenelle",
    "Cambron-Casteau",
    "Cannes",
    "Capellen",
    "Carlsbourg",
    "Carnieres",
    "Ceroux-Mousty",
    "Chambéry-Challes-les-Eaux",
    "Chapelle-Dieu",
    "Chapois",
    "Charleroi-Central",
    "Charleroi-Ouest",
    "Chastre",
    "Chaudfontaine",
    "Château-de-Seilles",
    "Châtelet",
    "Chênée",
    "Ciney",
    "Clervaux",
    "Colmar",
    "Comblain-la-Tour",
    "Coo",
    "Couillet",
    "Cour-sur-Heure",
    "Courcelles-Motte",
    "Courrière",
    "Court-Saint-Étienne",
    "Couvin",
    "Creil",
    "Croix Wasquehal",
    "Croix l'Allumette",
    "Dave-Saint-Martin",
    "De Hoek",
    "De Panne",
    "De Pinte",
    "Deinze",
    "Delta",
    "Den Haag HS",
    "Denderleeuw",
    "Dendermonde",
    "Diegem",
    "Diepenbeek",
    "Diesdelle/Vivier d'Oie",
    "Diest",
    "Diksmuide",
    "Dilbeek",
    "Dinant",
    "Dippach-Reckange",
    "Dolhain-Gileppe",
    "Dommeldange",
    "Dordrecht",
    "Dortmund Hbf",
    "Drauffelt",
    "Drongen",
    "Duesseldorf Flughafen (DE)",
    "Duffel",
    "Duinbergen",
    "Duisburg Hbf",
    "Dusseldorf Hbf",
    "Duesseldorf Hbf",
    "Düsseldorf Flughafen Hbf",
    "Ebbsfleet International",
    "Ede",
    "Edingen / Enghien",
    "Enghien",
    "Eeklo",
    "Eichem",
    "Eijsden",
    "Eine",
    "Eke-Nazareth",
    "Ekeren",
    "Engis",
    "Eppegem",
    "Erbisoeul",
    "Erbisœul",
    "Erembodegem",
    "Ernage",
    "Erpe-Mere",
    "Erps-Kwerps",
    "Erquelinnes",
    "Erquelinnes-Frontière",
    "Erquelinnes-Village",
    "Esneux",
    "Essen",
    "Essen Hbf",
    "Essen-Grens",
    "Essene-Lombeek",
    "Ettelbréck",
    "Etterbeek",
    "Eupen",
    "Evere",
    "Evergem",
    "Eygelshoven markt",
    "Ezemaal",
    "Familleureux",
    "Farciennes",
    "Faux",
    "Fexhe-le-Haut-Clocher",
    "Flawinne",
    "Flemalle-Grande",
    "Flemalle-Haute",
    "Fleurus",
    "Floreffe",
    "Florenville",
    "Florival",
    "Florée",
    "Fontaine-Valmont",
    "Forchies",
    "Forrières",
    "Fraipont",
    "Frameries",
    "Franchimont",
    "Franière",
    "Frankfurt am Main Flughafen Fernbf",
    "Frankfurt am Main Flughafen Reginalbf",
    "Frankfurt am Main Hbf",
    "Froyennes",
    "Galmaarden",
    "Gastuche",
    "Gavere-Asper",
    "Gedinne",
    "Geel",
    "Gembloux",
    "Gendron-Celles",
    "Genk",
    "Genly",
    "Gentbrugge",
    "Genval",
    "Geraardsbergen",
    "Ghent-Dampoort",
    "Gent-Dampoort",
    "Ghent-Sint-Pieters",
    "Gent-Sint-Pieters",
    "Ghlin",
    "Glons",
    "Godarville",
    "Godinne",
    "Goebelsmühle",
    "Gontrode",
    "Gouvy",
    "Gouvy-Frontiere",
    "Gouy-lez-Pieton",
    "Graide",
    "Groenendaal",
    "Groot-Bijgaarden",
    "Grupont",
    "Haacht",
    "Haaltert",
    "Habay",
    "Hainin",
    "Halanzy",
    "Halle",
    "Ham-sur-Heure",
    "Ham-sur-Sambre",
    "Hambos",
    "Hamoir",
    "Hamont",
    "Hansbeke",
    "Harchies",
    "Harelbeke",
    "Haren",
    "Haren-Sud/Haren-Zuid",
    "Hasselt",
    "Haute-Flône",
    "Haute-Picardie TGV",
    "Haversin",
    "Havre",
    "Heerlen",
    "Heide",
    "Heist",
    "Heist-op-den-Berg",
    "Heizijde",
    "Hellemmes",
    "Hemiksem",
    "Hennuyères",
    "Herent",
    "Herentals",
    "Hergenrath",
    "Hergenrath-Frontiere",
    "Herne",
    "Herseaux",
    "Herstal",
    "Herzele",
    "Herzogenrath",
    "Heusden",
    "Hever",
    "Heverlee",
    "Hillegem",
    "Hoboken-Polder",
    "Hoeilaart",
    "Hofstade",
    "Holleken",
    "Hollerich",
    "Hony",
    "Houraing",
    "Hourpes",
    "Houyet",
    "Hove",
    "Huizingen",
    "Huy",
    "Idar-Oberstein",
    "Iddergem",
    "Idegem",
    "Ieper",
    "Ingelmunster",
    "Izegem",
    "Jambes",
    "Jambes-Est",
    "Jamioulx",
    "Jemappes",
    "Jemeppe-sur-Meuse",
    "Jemeppe-sur-Sambre",
    "Jette",
    "Jurbise",
    "Jurbeke",
    "Juslenville",
    "Kalmthout",
    "Kapelle-op-den-Bos",
    "Kapellen",
    "Kautebaach",
    "Kessel",
    "Kiewit",
    "Kijkuit",
    "Klengbetten",
    "Knokke",
    "Koblenz Hbf",
    "Koksijde",
    "Komen / Comines",
    "Comines",
    "Kontich-Lint",
    "Kortemark",
    "Kortenberg",
    "Kortrijk",
    "Kwatrecht",
    "Köln Hbf",
    "La Hulpe",
    "La Louvière-Centre",
    "La Louvière-Sud",
    "La Roche (Brabant)",
    "Labuissière",
    "Lamadeleine",
    "Landegem",
    "Landelies",
    "Landen",
    "Landgraaf",
    "Landry",
    "Landskouter",
    "Langdorp",
    "Le Campinaire",
    "Lebbeke",
    "Lede",
    "Leignon",
    "Lelystad Centrum",
    "Leman",
    "Lembeek",
    "Lens",
    "Leopoldsburg",
    "Les Arcs - Draguignan",
    "Lessines",
    "Lessen",
    "Leudelange",
    "Leuven",
    "Leuze",
    "Leval",
    "Lezennes",
    "Libramont",
    "Lichtervelde",
    "Liedekerke",
    "Lier",
    "Lierde",
    "Liers",
    "Ligny",
    "Lille Europe",
    "Lille Flandres",
    "Lillois",
    "Limal",
    "Limburg Süd",
    "Linkebeek",
    "Lissewege",
    "Liège-Carré",
    "Liège-Guillemins",
    "Liège-Saint-Lambert",
    "Lobbes",
    "Lodelinsart",
    "Lokeren",
    "Lommel",
    "Londerzeel",
    "London Saint Pancras International",
    "London Waterloo",
    "Lonzée",
    "Lorraine TGV",
    "Lot",
    "Louvain-la-Neuve",
    "Lustin",
    "Luttre",
    "Lyon Part Dieu TGV",
    "Lyon-Perrache TGV",
    "Lyon-Saint Exupéry TGV",
    "Lëtzebuerg",
    "Maastricht",
    "Maastricht Randwyck",
    "Maffle",
    "Mainz Hbf",
    "Malderen",
    "Mamer",
    "Mamer-Lycée",
    "Manage",
    "Mannheim Hbf",
    "Marbehan",
    "Marche-en-Famenne",
    "Marche-les-Dames",
    "Marche-lez-Écaussinnes",
    "Marchienne-Zone",
    "Marchienne-au-Pont",
    "Maria-Aalter",
    "Mariembourg",
    "Marloie",
    "Marne-la-Vallée - Chessy",
    "Marseille-Saint-Charles",
    "Masnuy-Saint-Pierre",
    "Massy TGV",
    "Maubeuge",
    "Maubray",
    "Mazy",
    "Mechelen",
    "Mechelen-Nekkerspoel",
    "Meer-Grens",
    "Meerssen",
    "Meiser",
    "Melkouwen",
    "Melle",
    "Melle PW",
    "Melreux-Hotton",
    "Melsele",
    "Menen",
    "Merchtem",
    "Merelbeke",
    "Merode",
    "Mersch",
    "Messancy",
    "Metz",
    "Mevergnies-Attre",
    "Michelau",
    "Milmort",
    "Moensberg",
    "Moeskroen / Mouscron",
    "Mouscron",
    "Mol",
    "Mollem",
    "Momalle",
    "Mons",
    "Mont-Saint-Guibert",
    "Montpellier",
    "Montpellier-Sud-de-France",
    "Moortsele",
    "Morlanwelz",
    "Mortsel",
    "Mortsel-Deurnesteenweg",
    "Mortsel-Liersesteenweg",
    "Mortsel-Oude God",
    "Mouscron-Frontiere",
    "Moustier",
    "Mouterij",
    "Mouterij/Germoir",
    "Moûtiers-Salins-Brides-les-Bai",
    "Muizen",
    "Mulhouse",
    "Munkzwalm",
    "Méry",
    "Namur",
    "Namêche",
    "Naninne",
    "Nantes",
    "Narbonne",
    "Natoye",
    "Neerpelt",
    "Neerwinden",
    "Nessonvaux",
    "Neufchâteau",
    "Neufvilles",
    "Nice Ville",
    "Niel",
    "Nieuwkerken-Waas",
    "Nijlen",
    "Nimy",
    "Ninove",
    "Nivelles",
    "Noorderkempen (brecht)",
    "Noorderkempen",
    "Nossegem",
    "Nîmes",
    "Obaix-Buzet",
    "Obourg",
    "Okegem",
    "Olen",
    "Oostende",
    "Oostkamp",
    "Opwijk",
    "Ottignies",
    "Oud-Heverlee",
    "Oudegem",
    "Oudenaarde",
    "Ougrée",
    "Overpelt",
    "Paliseul",
    "Papignies",
    "Papegem",
    "Paris Nord",
    "Pepinster",
    "Pepinster-Cité",
    "Perpignan",
    "Petange",
    "Pfaffenthal-Kirchberg",
    "Philippeville",
    "Piéton",
    "Poix-Saint-Hubert",
    "Pont de Bois",
    "Pont-de-Seraing",
    "Pont-à-Celles",
    "Poperinge",
    "Poulseur",
    "Prague Central Station",
    "Praha Hlavní Nádraží",
    "Profondsart",
    "Pry",
    "Puurs",
    "Pécrot",
    "Péruwelz",
    "Quaregnon",
    "Quevy",
    "Quevy-frontiere",
    "Quievrain",
    "Rebaix",
    "Remicourt",
    "Rennes",
    "Rhisnes",
    "Rivage",
    "Rixensart",
    "Rochefort-Jemelle",
    "Rodange",
    "Roeselare",
    "Ronet",
    "Ronse / Renaix",
    "Ronse",
    "Roosendaal",
    "Rotterdam CS",
    "Roubaix",
    "Roux",
    "Ruisbroek",
    "Ruisbroek-Sauvegarde",
    "Saint-Denis-Bovesse",
    "Saint-Ghislain",
    "Saint-Louis-Haut-Rhin",
    "Saint-Raphaël-Valescure",
    "Sart-Bernard",
    "Saverne",
    "Schaarbeek/Schaerbeek",
    "Scheldewindeke",
    "Schelle",
    "Schellebelle",
    "Schendelbeke",
    "Schiphol",
    "Schoonaarde",
    "Schouweiler",
    "Schulen",
    "Sclaigneaux",
    "Sclessin",
    "Selestat",
    "Seraing",
    "Serskamp",
    "Siegburg",
    "Silly",
    "Simonis",
    "Sinaai",
    "Sint-Agatha-Berchem/Berchem-Sainte-Agathe",
    "Sint-Denijs-Boekel",
    "Sint-Gillis",
    "Sint-Gillis-Dendermonde",
    "Sint-Job / Saint-Job",
    "Sint-Job",
    "Sint-Joris-Weert",
    "Sint-Katelijne-Waver",
    "Sint-Mariaburg",
    "Sint-Martens-Bodegem",
    "Sint-Niklaas",
    "Sint-Truiden",
    "Sleidinge",
    "Soignies",
    "Solre-sur-Sambre",
    "Spa",
    "Spa-Géronstère",
    "St.-Genesius-Rode/rhode-St.-Genese",
    "Sint-Genesius-Rode",
    "Statte",
    "Sterpenich-Frontiere",
    "Stockem",
    "Strasbourg",
    "Sy",
    "Sète",
    "Tamines",
    "Temse",
    "Terhagen",
    "Ternat",
    "Testelt",
    "Theux",
    "Thieu",
    "Thionville",
    "Thuin",
    "Thulin",
    "Thurn en Taxis",
    "Thurn en Taxis/Tour et Taxis",
    "Tielen",
    "Tielt",
    "Tienen",
    "Tilff",
    "Tilly",
    "Tollembeek",
    "Tongeren",
    "Torhout",
    "Toulon",
    "Tourcoing",
    "Tournai",
    "Trois-Ponts",
    "Troisvierges",
    "Trooz",
    "Tubize",
    "Turnhout",
    "Ukkel-Kalevoet/Uccle-Calevoet",
    "Ukkel-Stalle/Uccle-Stalle",
    "Utrecht Centraal",
    "Valence TGV",
    "Valkenburg",
    "Veltem",
    "Venezia Santa Lucia",
    "Vertrijk",
    "Verviers-Central",
    "Verviers-Palais",
    "Veurne",
    "Viane-Moerbeke",
    "Vichte",
    "Vielsalm",
    "Vienna Main Station",
    "Wien Hbf",
    "Vijfhuizen",
    "Ville-Pommerœul",
    "Villers-la-Ville",
    "Vilvoorde",
    "Virton",
    "Vise-Frontiere",
    "Visé",
    "Viville",
    "Voroux",
    "Vorst-Oost/Forest-Est",
    "Vorst-Zuid/Forest-Midi",
    "Waarschoot",
    "Walcourt",
    "Waregem",
    "Waremme",
    "Waterloo",
    "Watermaal/Watermael",
    "Wavre",
    "Weerde",
    "Welkenraedt",
    "Welle",
    "Wervik",
    "Wespelaar-Tildonk",
    "Wetteren",
    "Wevelgem",
    "Wezemaal",
    "Wichelen",
    "Wijgmaal",
    "Wildert",
    "Willebroek",
    "Wilwerwiltz",
    "Wolfstee",
    "Wondelgem",
    "Y.renory",
    "Yves-Gomezée",
    "Yvoir",
    "Zandbergen",
    "Zaventem",
    "Zedelgem",
    "Zeebrugge-Dorp",
    "Zeebrugge-Strand",
    "Zele",
    "Zellik",
    "Zichem",
    "Zingem",
    "Zolder",
    "Zonhoven",
    "Zottegem",
    "Zwankendamme",
    "Zwijndrecht",
    "Zwijndrecht-Dorp",
    "Écaussinnes",
]

phrase_list_nl: list[str] = [
    "'s Gravenbrakel",
    "Braine-le-Comte",
    "'s Hertogenbosch",
    "Aalst",
    "Aalst-Kerrebroek",
    "Aalter",
    "Aarlen",
    "Arlon",
    "Aarschot",
    "Aarsele",
    "Aat",
    "Ath",
    "Agde",
    "Aime-la-Plagne",
    "Aiseau",
    "Aix-en-Provence TGV",
    "Aken Hbf",
    "Aachen Hbf",
    "Aken West",
    "Aachen West",
    "Akren",
    "Acren",
    "Albertville",
    "Alken",
    "Almere Buiten",
    "Almere Centrum",
    "Amay",
    "Ampsin",
    "Amsterdam CS",
    "Amsterdam Centraal",
    "Amsterdam Zuid",
    "Andenne",
    "Anderlecht",
    "Angleur",
    "Annappes",
    "Ans",
    "Anseremme",
    "Antibes",
    "Antoing",
    "Antwerpen-Berchem",
    "Antwerpen-Centraal",
    "Antwerpen-Dam",
    "Antwerpen-Haven",
    "Antwerpen-Linkeroever",
    "Antwerpen-Luchtbal",
    "Antwerpen-Noorderdokken",
    "Antwerpen-Oost",
    "Antwerpen-Zuid",
    "Anzegem",
    "Appelterre",
    "Arcaden",
    "Arcaden/Arcades",
    "Arras",
    "Ascq",
    "Asse",
    "Assesse",
    "Athus",
    "Athus-Frontiere",
    "Aubange",
    "Aubange-Frontiere-Luxembourg",
    "Aulnoye-Aymeries",
    "Auvelais",
    "Avignon TGV",
    "Aye",
    "Aywaille",
    "Aéroport Charles-de-Gaulle TGV",
    "Baasrode-Zuid",
    "Baisieux",
    "Balegem-Dorp",
    "Balegem-Zuid",
    "Balen",
    "Bambrugge",
    "Barvaux",
    "Bas-Oha",
    "Bascharage-Sanem",
    "Basse-Wavre",
    "Bastenaken-Noord",
    "Bastogne-Nord",
    "Bastenaken-Zuid",
    "Bastogne-Sud",
    "Bazel",
    "Basel",
    "Beauraing",
    "Beernem",
    "Beersel",
    "Beervelde",
    "Begijnendijk",
    "Beignée",
    "Bellem",
    "Belsele",
    "Bergen",
    "Mons",
    "Beringen",
    "Berlaar",
    "Berlin HBF",
    "Berlin Lichtenberg",
    "Berlin Ostbahnhof",
    "Bertrange Strassen",
    "Bertrix",
    "Berzée",
    "Beuzet",
    "Beveren",
    "Beverlo",
    "Bierges-Walibi",
    "Bierset-Awans",
    "Bilzen",
    "Binche",
    "Bissegem",
    "Blandain-Frontiere",
    "Blankenberge",
    "Blanmont",
    "Blaton",
    "Bleret",
    "Bockstael",
    "Boechout",
    "Bokrijk",
    "Bomal",
    "Bonn-Beuel",
    "Booischot",
    "Boom",
    "Boondaal",
    "Boondaal/Boondael",
    "Boortmeerbeek",
    "Bordeaux Saint Jean",
    "Bordet",
    "Borgworm",
    "Waremme",
    "Bornem",
    "Bosvoorde",
    "Bosvoorde/Boitsfort",
    "Bourg-Saint-Maurice",
    "Boussu",
    "Bouwel",
    "Bracquegnies",
    "Breda",
    "Bressoux",
    "Brugelette",
    "Brugge",
    "Brugge-Sint-Pieters",
    "Brussel-Centraal",
    "Brussel-Centraal/Bruxelles-Central",
    "Brussel-Congres",
    "Brussel-Congres/Bruxelles-Congrès",
    "Brussel-Kapellekerk",
    "Brussel-Kapellekerk/Bruxelles-Chapelle",
    "Brussel-Luxemburg",
    "Brussel-Luxemburg/Bruxelles-Luxembourg",
    "Brussel-Noord",
    "Brussel-Noord/Bruxelles-Nord",
    "Brussel-Schuman",
    "Brussel-Schuman/Bruxelles-Schuman",
    "Brussel-West",
    "Brussel-West/Bruxelles-Ouest",
    "Brussel-Zuid",
    "Brussel-Zuid/Bruxelles-Midi",
    "Brussels Airport - Zaventem",
    "Buda",
    "Buggenhout",
    "Buizingen",
    "Burst",
    "Béziers",
    "Callenelle",
    "Cambron-Casteau",
    "Cannes",
    "Capellen",
    "Carlsbourg",
    "Carnieres",
    "Ceroux-Mousty",
    "Chambéry-Challes-les-Eaux",
    "Chapelle-Dieu",
    "Chapois",
    "Charleroi-Centraal",
    "Charleroi-Central",
    "Charleroi-West",
    "Charleroi-Ouest",
    "Chastre",
    "Chaudfontaine",
    "Château-de-Seilles",
    "Châtelet",
    "Chênée",
    "Ciney",
    "Clervaux",
    "Colmar",
    "Comblain-la-Tour",
    "Coo",
    "Couillet",
    "Cour-sur-Heure",
    "Courcelles-Motte",
    "Courrière",
    "Court-Saint-Étienne",
    "Couvin",
    "Creil",
    "Croix Wasquehal",
    "Croix l'Allumette",
    "Dave-Saint-Martin",
    "De Hoek",
    "De Panne",
    "De Pinte",
    "Deinze",
    "Delta",
    "Den Haag HS",
    "Denderleeuw",
    "Dendermonde",
    "Diegem",
    "Diepenbeek",
    "Diesdelle",
    "Diesdelle/Vivier d'Oie",
    "Diest",
    "Diksmuide",
    "Dilbeek",
    "Dinant",
    "Dippach-Reckange",
    "Dolhain-Gileppe",
    "Dommeldange",
    "Doornik",
    "Tournai",
    "Dordrecht",
    "Dortmund Hbf",
    "Drauffelt",
    "Drongen",
    "Duesseldorf Flughafen (DE)",
    "Duffel",
    "Duinbergen",
    "Duisburg Hbf",
    "Düsseldorf Flughafen Hbf",
    "Düsseldorf Hbf",
    "Duesseldorf Hbf",
    "Ebbsfleet International",
    "Ede",
    "Edingen",
    "Enghien",
    "Eeklo",
    "Eerken",
    "Archennes",
    "Eichem",
    "Eigenbrakel",
    "Braine-l'Alleud",
    "Eijsden",
    "Eine",
    "Eke-Nazareth",
    "Ekeren",
    "Engis",
    "Eppegem",
    "Erbisoeul",
    "Erbisœul",
    "Erembodegem",
    "Ernage",
    "Erpe-Mere",
    "Erps-Kwerps",
    "Erquelinnes",
    "Erquelinnes-Frontière",
    "Erquelinnes-Village",
    "Esneux",
    "Essen",
    "Essen Hbf",
    "Essen-Grens",
    "Essene-Lombeek",
    "Ettelbruck",
    "Ettelbréck",
    "Etterbeek",
    "Eupen",
    "Evere",
    "Evergem",
    "Eygelshoven markt",
    "Ezemaal",
    "Familleureux",
    "Farciennes",
    "Faux",
    "Fexhe-le-Haut-Clocher",
    "Flawinne",
    "Flemalle-Grande",
    "Flemalle-Haute",
    "Fleurus",
    "Floreffe",
    "Florenville",
    "Florival",
    "Florée",
    "Fontaine-Valmont",
    "Forchies",
    "Forrières",
    "Fraipont",
    "Frameries",
    "Franchimont",
    "Franière",
    "Frankfurt am Main Flughafen Fernbf",
    "Frankfurt am Main Flughafen Reginalbf",
    "Frankfurt am Main Hbf",
    "Froyennes",
    "Galmaarden",
    "Gastuche",
    "Gavere-Asper",
    "Gedinne",
    "Geel",
    "Gembloux",
    "Gendron-Celles",
    "Genk",
    "Genly",
    "Gent-Dampoort",
    "Gent-Sint-Pieters",
    "Gentbrugge",
    "Genval",
    "Geraardsbergen",
    "Ghlin",
    "Glaaien",
    "Glons",
    "Godarville",
    "Godinne",
    "Goebelsmühle",
    "Gontrode",
    "Gouvy",
    "Gouvy-Frontiere",
    "Gouy-lez-Pieton",
    "Graide",
    "Groenendaal",
    "Groot-Bijgaarden",
    "Grupont",
    "Haacht",
    "Haaltert",
    "Habay",
    "Hainin",
    "Halanzy",
    "Halle",
    "Ham-sur-Heure",
    "Ham-sur-Sambre",
    "Hambos",
    "Hamoir",
    "Hamont",
    "Hansbeke",
    "Harchies",
    "Harelbeke",
    "Haren",
    "Haren-Zuid",
    "Haren-Sud/Haren-Zuid",
    "Hasselt",
    "Haute-Flône",
    "Haute-Picardie TGV",
    "Haversin",
    "Havre",
    "Heerlen",
    "Heide",
    "Heist",
    "Heist-op-den-Berg",
    "Heizijde",
    "Hellemmes",
    "Hemiksem",
    "Hennuyères",
    "Herent",
    "Herentals",
    "Hergenrath",
    "Hergenrath-Frontiere",
    "Herne",
    "Herseaux",
    "Herstal",
    "Herzele",
    "Herzogenrath",
    "Heusden",
    "Hever",
    "Heverlee",
    "Hillegem",
    "Hoboken-Polder",
    "Hoei",
    "Huy",
    "Hoeilaart",
    "Hofstade",
    "Holleken",
    "Hollerich",
    "Hony",
    "Houraing",
    "Hourpes",
    "Houyet",
    "Hove",
    "Huizingen",
    "Idar-Oberstein",
    "Iddergem",
    "Idegem",
    "Ieper",
    "Ingelmunster",
    "Izegem",
    "Jambes",
    "Jambes-Est",
    "Jamioulx",
    "Jemappes",
    "Jemeppe-sur-Meuse",
    "Jemeppe-sur-Sambre",
    "Jette",
    "Jurbeke",
    "Juslenville",
    "Kalmthout",
    "Kapelle-op-den-Bos",
    "Kapellen",
    "Kautenbach",
    "Kautebaach",
    "Kessel",
    "Keulen Hbf",
    "Köln Hbf",
    "Kiewit",
    "Kijkuit",
    "Kleinbettingen",
    "Klengbetten",
    "Knokke",
    "Koblenz Hbf",
    "Koksijde",
    "Komen",
    "Comines",
    "Kontich-Lint",
    "Kortemark",
    "Kortenberg",
    "Kortrijk",
    "Kwatrecht",
    "La Louvière-Centrum",
    "La Louvière-Centre",
    "La Louvière-Zuid",
    "La Louvière-Sud",
    "La Roche (Brabant)",
    "Labuissière",
    "Lamadeleine",
    "Landegem",
    "Landelies",
    "Landen",
    "Landgraaf",
    "Landry",
    "Landskouter",
    "Langdorp",
    "Le Campinaire",
    "Lebbeke",
    "Lede",
    "Leignon",
    "Lelystad Centrum",
    "Leman",
    "Lembeek",
    "Lens",
    "Leopoldsburg",
    "Les Arcs - Draguignan",
    "Lessen",
    "Leudelange",
    "Leuven",
    "Leuze",
    "Leval",
    "Lezennes",
    "Libramont",
    "Lichtervelde",
    "Liedekerke",
    "Lier",
    "Lierde",
    "Liers",
    "Ligny",
    "Lillois",
    "Limal",
    "Limburg Süd",
    "Linkebeek",
    "Lissewege",
    "Lobbes",
    "Lodelinsart",
    "Lokeren",
    "Lommel",
    "Londen Saint Pancras",
    "London Saint Pancras International",
    "Londen Waterloo",
    "London Waterloo",
    "Londerzeel",
    "Lonzée",
    "Lorraine TGV",
    "Lot",
    "Louvain-la-Neuve",
    "Luik-Carre",
    "Liège-Carré",
    "Luik-Guillemins",
    "Liège-Guillemins",
    "Luik-Sint-Lambertus",
    "Liège-Saint-Lambert",
    "Lustin",
    "Luttre",
    "Luxemburg",
    "Lëtzebuerg",
    "Lyon Part Dieu TGV",
    "Lyon-Perrache TGV",
    "Lyon-Saint Exupéry TGV",
    "Maastricht",
    "Maastricht Randwyck",
    "Maffle",
    "Mainz Hbf",
    "Malderen",
    "Mamer",
    "Mamer-Lycée",
    "Manage",
    "Mannheim Hbf",
    "Marbehan",
    "Marche-en-Famenne",
    "Marche-les-Dames",
    "Marche-lez-Écaussinnes",
    "Marchienne-Zone",
    "Marchienne-au-Pont",
    "Maria-Aalter",
    "Mariembourg",
    "Marloie",
    "Marne-la-Vallée - Chessy",
    "Marseille-Saint-Charles",
    "Masnuy-Saint-Pierre",
    "Massy TGV",
    "Maubeuge",
    "Maubray",
    "Mazy",
    "Mechelen",
    "Mechelen-Nekkerspoel",
    "Meer-Grens",
    "Meerssen",
    "Meiser",
    "Melkouwen",
    "Melle",
    "Melle PW",
    "Melreux-Hotton",
    "Melsele",
    "Menen",
    "Merchtem",
    "Merelbeke",
    "Merode",
    "Mersch",
    "Messancy",
    "Metz",
    "Mevergnies-Attre",
    "Michelau",
    "Milmort",
    "Moensberg",
    "Moeskroen",
    "Mouscron",
    "Moeskroen-Grens",
    "Mouscron-Frontiere",
    "Mol",
    "Mollem",
    "Momalle",
    "Mont-Saint-Guibert",
    "Montpellier",
    "Montpellier-Sud-de-France",
    "Moortsele",
    "Morlanwelz",
    "Mortsel",
    "Mortsel-Deurnesteenweg",
    "Mortsel-Liersesteenweg",
    "Mortsel-Oude God",
    "Moustier",
    "Mouterij",
    "Mouterij/Germoir",
    "Moûtiers-Salins-Brides-les-Bai",
    "Muizen",
    "Mulhouse",
    "Munkzwalm",
    "Méry",
    "Namen",
    "Namur",
    "Namêche",
    "Naninne",
    "Nantes",
    "Narbonne",
    "Natoye",
    "Neerpelt",
    "Neerwinden",
    "Nessonvaux",
    "Neufchâteau",
    "Neufvilles",
    "Nice Ville",
    "Niel",
    "Nieuwkerken-Waas",
    "Nijlen",
    "Nijvel",
    "Nivelles",
    "Nimy",
    "Ninove",
    "Noorderkempen",
    "Nossegem",
    "Nîmes",
    "Obaix-Buzet",
    "Obourg",
    "Okegem",
    "Olen",
    "Oostende",
    "Oostkamp",
    "Opwijk",
    "Opzullik",
    "Silly",
    "Ottignies",
    "Oud-Heverlee",
    "Oudegem",
    "Oudenaarde",
    "Ougrée",
    "Overpelt",
    "Paliseul",
    "Papegem",
    "Parijs Noord",
    "Paris Nord",
    "Pepinster",
    "Pepinster-Cité",
    "Perpignan",
    "Petange",
    "Pfaffenthal-Kirchberg",
    "Philippeville",
    "Piéton",
    "Poix-Saint-Hubert",
    "Pont de Bois",
    "Pont-de-Seraing",
    "Pont-à-Celles",
    "Poperinge",
    "Poulseur",
    "Praag hoofdstation",
    "Praha Hlavní Nádraží",
    "Profondsart",
    "Pry",
    "Puurs",
    "Pécrot",
    "Péruwelz",
    "Quaregnon",
    "Quevy",
    "Quevy-frontiere",
    "Quievrain",
    "Rebaix",
    "Remicourt",
    "Rennes",
    "Rhisnes",
    "Rijsel-Europa",
    "Lille Europe",
    "Rijsel-Vlaanderen",
    "Lille Flandres",
    "Rivage",
    "Rixensart",
    "Rochefort-Jemelle",
    "Rodange",
    "Roeselare",
    "Ronet",
    "Ronse",
    "Roosendaal",
    "Rotterdam CS",
    "Roubaix",
    "Roux",
    "Ruisbroek",
    "Ruisbroek-Sauvegarde",
    "Saint-Denis-Bovesse",
    "Saint-Ghislain",
    "Saint-Louis-Haut-Rhin",
    "Saint-Raphaël-Valescure",
    "Sart-Bernard",
    "Saverne",
    "Schaarbeek",
    "Schaarbeek/Schaerbeek",
    "Scheldewindeke",
    "Schelle",
    "Schellebelle",
    "Schendelbeke",
    "Schiphol",
    "Schoonaarde",
    "Schouweiler",
    "Schulen",
    "Sclaigneaux",
    "Sclessin",
    "Selestat",
    "Seraing",
    "Serskamp",
    "Siegburg",
    "Simonis",
    "Sinaai",
    "Sint-Agatha-Berchem",
    "Sint-Agatha-Berchem/Berchem-Sainte-Agathe",
    "Sint-Denijs-Boekel",
    "Sint-Genesius-Rode",
    "Sint-Gillis",
    "Sint-Gillis-Dendermonde",
    "Sint-Job",
    "Sint-Joris-Weert",
    "Sint-Katelijne-Waver",
    "Sint-Mariaburg",
    "Sint-Martens-Bodegem",
    "Sint-Niklaas",
    "Sint-Truiden",
    "Sleidinge",
    "Solre-sur-Sambre",
    "Spa",
    "Spa-Géronstère",
    "Statte",
    "Sterpenich-Frontiere",
    "Stockem",
    "Straatsburg",
    "Strasbourg",
    "Sy",
    "Sète",
    "Tamines",
    "Temse",
    "Terhagen",
    "Terhulpen",
    "La Hulpe",
    "Ternat",
    "Testelt",
    "Theux",
    "Thieu",
    "Thionville",
    "Thuin",
    "Thulin",
    "Thurn en Taxis",
    "Thurn en Taxis/Tour et Taxis",
    "Tielen",
    "Tielt",
    "Tienen",
    "Tilff",
    "Tilly",
    "Tollembeek",
    "Tongeren",
    "Torhout",
    "Toulon",
    "Tourcoing",
    "Trois-Ponts",
    "Troisvierges",
    "Trooz",
    "Tubeke",
    "Tubize",
    "Turnhout",
    "Ukkel-Kalevoet",
    "Ukkel-Kalevoet/Uccle-Calevoet",
    "Ukkel-Stalle",
    "Ukkel-Stalle/Uccle-Stalle",
    "Utrecht Centraal",
    "Valence TGV",
    "Valkenburg",
    "Veltem",
    "Venezia Santa Lucia",
    "Vertrijk",
    "Verviers-Centraal",
    "Verviers-Central",
    "Verviers-Paleis",
    "Verviers-Palais",
    "Veurne",
    "Viane-Moerbeke",
    "Vichte",
    "Vielsalm",
    "Vijfhuizen",
    "Ville-Pommerœul",
    "Villers-la-Ville",
    "Vilvoorde",
    "Virton",
    "Vise-Frontiere",
    "Viville",
    "Voroux",
    "Vorst-Oost",
    "Vorst-Oost/Forest-Est",
    "Vorst-Zuid",
    "Vorst-Zuid/Forest-Midi",
    "Waarschoot",
    "Walcourt",
    "Waregem",
    "Waterloo",
    "Watermaal",
    "Watermaal/Watermael",
    "Waver",
    "Wavre",
    "Weerde",
    "Welkenraedt",
    "Welle",
    "Wervik",
    "Wespelaar-Tildonk",
    "Wetteren",
    "Wevelgem",
    "Wezemaal",
    "Wezet",
    "Visé",
    "Wichelen",
    "Wien Hbf",
    "Wijgmaal",
    "Wildert",
    "Willebroek",
    "Wilwerwiltz",
    "Wolfstee",
    "Wondelgem",
    "Y.renory",
    "Yves-Gomezée",
    "Yvoir",
    "Zandbergen",
    "Zaventem",
    "Zedelgem",
    "Zeebrugge-Dorp",
    "Zeebrugge-Strand",
    "Zele",
    "Zellik",
    "Zichem",
    "Zingem",
    "Zinnik",
    "Soignies",
    "Zolder",
    "Zonhoven",
    "Zottegem",
    "Zwankendamme",
    "Zwijndrecht",
    "Zwijndrecht-Dorp",
    "Écaussinnes",
]

phrase_list_fr: list[str] = [
    "'s Hertogenbosch",
    "Aalter",
    "Aarschot",
    "Aarsele",
    "Acren",
    "Agde",
    "Aime-la-Plagne",
    "Aiseau",
    "Aix-en-Provence TGV",
    "Aix-la-Chapelle Hbf",
    "Aachen Hbf",
    "Aix-la-Chapelle Ouest",
    "Aachen West",
    "Albertville",
    "Alken",
    "Almere Buiten",
    "Almere Centrum",
    "Alost",
    "Aalst",
    "Alost Kerrebroek",
    "Aalst-Kerrebroek",
    "Amay",
    "Ampsin",
    "Amsterdam CS",
    "Amsterdam Centraal",
    "Amsterdam Zuid",
    "Andenne",
    "Anderlecht",
    "Angleur",
    "Annappes",
    "Ans",
    "Anseremme",
    "Antibes",
    "Antoing",
    "Anvers-Berchem",
    "Antwerpen-Berchem",
    "Anvers-Central",
    "Antwerpen-Centraal",
    "Anvers-Dam",
    "Antwerpen-Dam",
    "Anvers-Est",
    "Antwerpen-Oost",
    "Anvers-Haven",
    "Antwerpen-Haven",
    "Anvers-Linkeroever",
    "Antwerpen-Linkeroever",
    "Anvers-Luchtbal",
    "Antwerpen-Luchtbal",
    "Anvers-Noorderdokken",
    "Antwerpen-Noorderdokken",
    "Anvers-Sud",
    "Antwerpen-Zuid",
    "Anzegem",
    "Appelterre",
    "Arcades",
    "Arcaden/Arcades",
    "Archennes",
    "Arlon",
    "Arras",
    "Ascq",
    "Asse",
    "Assesse",
    "Ath",
    "Athus",
    "Athus-Frontiere",
    "Aubange",
    "Aubange-Frontiere-Luxembourg",
    "Audenarde",
    "Oudenaarde",
    "Aulnoye-Aymeries",
    "Auvelais",
    "Avignon TGV",
    "Aye",
    "Aywaille",
    "Aéroport Charles-de-Gaulle TGV",
    "Baelen",
    "Balen",
    "Baesrode-Sud",
    "Baasrode-Zuid",
    "Baisieux",
    "Balegem-Dorp",
    "Balegem-Zuid",
    "Bambrugge",
    "Barvaux",
    "Bas-Oha",
    "Bascharage-Sanem",
    "Basel",
    "Basse-Wavre",
    "Bastogne-Nord",
    "Bastogne-Sud",
    "Beauraing",
    "Beernem",
    "Beersel",
    "Beervelde",
    "Begijnendijk",
    "Beignée",
    "Bellem",
    "Belsele",
    "Berchem-Sainte-Agathe",
    "Sint-Agatha-Berchem/Berchem-Sainte-Agathe",
    "Beringen",
    "Berlaar",
    "Berlin HBF",
    "Berlin Lichtenberg",
    "Berlin Ostbahnhof",
    "Bertrange Strassen",
    "Bertrix",
    "Berzée",
    "Beuzet",
    "Beveren",
    "Beverlo",
    "Bierges-Walibi",
    "Bierset-Awans",
    "Bilzen",
    "Binche",
    "Bissegem",
    "Blandain-Frontiere",
    "Blankenberge",
    "Blanmont",
    "Blaton",
    "Bleret",
    "Bockstael",
    "Bodeghem-Saint-Martin",
    "Sint-Martens-Bodegem",
    "Boechout",
    "Boitsfort",
    "Bosvoorde/Boitsfort",
    "Bokrijk",
    "Bomal",
    "Bonn-Beuel",
    "Booischot",
    "Boom",
    "Boondael",
    "Boondaal/Boondael",
    "Boortmeerbeek",
    "Bordeaux Saint Jean",
    "Bordet",
    "Bornem",
    "Bourg-Léopold",
    "Leopoldsburg",
    "Bourg-Saint-Maurice",
    "Boussu",
    "Bouwel",
    "Bracquegnies",
    "Braine-l'Alleud",
    "Braine-le-Comte",
    "Breda",
    "Bressoux",
    "Brugelette",
    "Bruges",
    "Brugge",
    "Bruges-Saint-Pierre",
    "Brugge-Sint-Pieters",
    "Brussels Airport - Zaventem",
    "Bruxelles-Central",
    "Brussel-Centraal/Bruxelles-Central",
    "Bruxelles-Chapelle",
    "Brussel-Kapellekerk/Bruxelles-Chapelle",
    "Bruxelles-Congrès",
    "Brussel-Congres/Bruxelles-Congrès",
    "Bruxelles-Luxembourg",
    "Brussel-Luxemburg/Bruxelles-Luxembourg",
    "Bruxelles-Midi",
    "Brussel-Zuid/Bruxelles-Midi",
    "Bruxelles-Nord",
    "Brussel-Noord/Bruxelles-Nord",
    "Bruxelles-Ouest",
    "Brussel-West/Bruxelles-Ouest",
    "Bruxelles-Schuman",
    "Brussel-Schuman/Bruxelles-Schuman",
    "Buda",
    "Buggenhout",
    "Buizingen",
    "Burst",
    "Béziers",
    "Callenelle",
    "Cambron-Casteau",
    "Cannes",
    "Capellen",
    "Carlsbourg",
    "Carnieres",
    "Ceroux-Mousty",
    "Chambéry-Challes-les-Eaux",
    "Chapelle-Dieu",
    "Chapois",
    "Charleroi-Central",
    "Charleroi-Ouest",
    "Chastre",
    "Chaudfontaine",
    "Château-de-Seilles",
    "Châtelet",
    "Chênée",
    "Ciney",
    "Clervaux",
    "Colmar",
    "Cologne Hbf",
    "Köln Hbf",
    "Comblain-la-Tour",
    "Comines",
    "Coo",
    "Couillet",
    "Cour-sur-Heure",
    "Courcelles-Motte",
    "Courrière",
    "Court-Saint-Étienne",
    "Courtrai",
    "Kortrijk",
    "Couvin",
    "Coxyde",
    "Koksijde",
    "Creil",
    "Croix Wasquehal",
    "Croix l'Allumette",
    "Dave-Saint-Martin",
    "De Hoek",
    "De Pinte",
    "Deinze",
    "Delta",
    "Den Haag HS",
    "Denderleeuw",
    "Diegem",
    "Diepenbeek",
    "Diest",
    "Dilbeek",
    "Dinant",
    "Dippach-Reckange",
    "Dixmude",
    "Diksmuide",
    "Dolhain-Gileppe",
    "Dommeldange",
    "Dordrecht",
    "Dortmund Hbf",
    "Drauffelt",
    "Duesseldorf Flughafen (DE)",
    "Duffel",
    "Duinbergen",
    "Duisburg Hbf",
    "Düsseldorf Flughafen Hbf",
    "Düsseldorf Hbf",
    "Duesseldorf Hbf",
    "Ebbsfleet International",
    "Ede",
    "Eeklo",
    "Eichem",
    "Eijsden",
    "Eine",
    "Eke-Nazareth",
    "Ekeren",
    "Enghien",
    "Engis",
    "Eppegem",
    "Erbisoeul",
    "Erbisœul",
    "Erembodegem",
    "Ernage",
    "Erpe-Mere",
    "Erps-Kwerps",
    "Erquelinnes",
    "Erquelinnes-Frontière",
    "Erquelinnes-Village",
    "Esneux",
    "Essen",
    "Essen Hbf",
    "Essen-Grens",
    "Essene-Lombeek",
    "Ettelbruck",
    "Ettelbréck",
    "Etterbeek",
    "Eupen",
    "Evere",
    "Evergem",
    "Eygelshoven markt",
    "Ezemaal",
    "Familleureux",
    "Farciennes",
    "Faux",
    "Fexhe-le-Haut-Clocher",
    "Flawinne",
    "Flemalle-Grande",
    "Flemalle-Haute",
    "Fleurus",
    "Floreffe",
    "Florenville",
    "Florival",
    "Florée",
    "Fontaine-Valmont",
    "Forchies",
    "Forest-Est",
    "Vorst-Oost/Forest-Est",
    "Forest-Midi",
    "Vorst-Zuid/Forest-Midi",
    "Forrières",
    "Fraipont",
    "Frameries",
    "Francfort-sur-le-Main Hbf",
    "Frankfurt am Main Hbf",
    "Franchimont",
    "Franière",
    "Frankfurt am Main Flughafen Fernbf",
    "Frankfurt am Main Flughafen Reginalbf",
    "Froyennes",
    "Furnes",
    "Veurne",
    "Gammerages",
    "Galmaarden",
    "Gand-Dampoort",
    "Gent-Dampoort",
    "Gand-Saint-Pierre",
    "Gent-Sint-Pieters",
    "Gastuche",
    "Gavere-Asper",
    "Gedinne",
    "Geel",
    "Gembloux",
    "Gendron-Celles",
    "Genk",
    "Genly",
    "Gentbrugge",
    "Genval",
    "Germoir",
    "Mouterij/Germoir",
    "Ghlin",
    "Glons",
    "Godarville",
    "Godinne",
    "Goebelsmühle",
    "Gontrode",
    "Gouvy",
    "Gouvy-Frontiere",
    "Gouy-lez-Pieton",
    "Graide",
    "Grammont",
    "Geraardsbergen",
    "Grand-Bigard",
    "Groot-Bijgaarden",
    "Groenendael",
    "Groenendaal",
    "Grupont",
    "Haacht",
    "Haaltert",
    "Habay",
    "Hainin",
    "Hal",
    "Halle",
    "Halanzy",
    "Ham-sur-Heure",
    "Ham-sur-Sambre",
    "Hambos",
    "Hamoir",
    "Hamont",
    "Hansbeke",
    "Harchies",
    "Harelbeke",
    "Haren",
    "Haren-Sud",
    "Haren-Sud/Haren-Zuid",
    "Hasselt",
    "Haute-Flône",
    "Haute-Picardie TGV",
    "Haversin",
    "Havre",
    "Heerlen",
    "Heide",
    "Heist",
    "Heist-op-den-Berg",
    "Heizijde",
    "Hellemmes",
    "Hemiksem",
    "Hennuyères",
    "Herent",
    "Herentals",
    "Hergenrath",
    "Hergenrath-Frontiere",
    "Herne",
    "Herseaux",
    "Herstal",
    "Herzele",
    "Herzogenrath",
    "Heusden",
    "Hever",
    "Heverlee",
    "Hillegem",
    "Hoboken-Polder",
    "Hoeilaart",
    "Hofstade",
    "Holleken",
    "Hollerich",
    "Hony",
    "Houraing",
    "Hourpes",
    "Houyet",
    "Hove",
    "Huizingen",
    "Huy",
    "Idar-Oberstein",
    "Iddergem",
    "Idegem",
    "Ingelmunster",
    "Izegem",
    "Jambes",
    "Jambes-Est",
    "Jamioulx",
    "Jemappes",
    "Jemeppe-sur-Meuse",
    "Jemeppe-sur-Sambre",
    "Jette",
    "Jurbise",
    "Jurbeke",
    "Juslenville",
    "Kalmthout",
    "Kapelle-op-den-Bos",
    "Kapellen",
    "Kautenbach",
    "Kautebaach",
    "Kessel",
    "Kiewit",
    "Kijkuit",
    "Kleinbettingen",
    "Klengbetten",
    "Knokke",
    "Koblenz Hbf",
    "Kontich-Lint",
    "Kortemark",
    "Kortenberg",
    "La Hulpe",
    "La Louvière-Centre",
    "La Louvière-Sud",
    "La Panne",
    "De Panne",
    "La Roche (Brabant)",
    "Labuissière",
    "Lamadeleine",
    "Landegem",
    "Landelies",
    "Landen",
    "Landgraaf",
    "Landry",
    "Landskouter",
    "Langdorp",
    "Le Campinaire",
    "Lebbeke",
    "Lede",
    "Leignon",
    "Lelystad Centrum",
    "Leman",
    "Lembeek",
    "Lens",
    "Les Arcs - Draguignan",
    "Lessines",
    "Lessen",
    "Leudelange",
    "Leuze",
    "Leval",
    "Lezennes",
    "Libramont",
    "Lichtervelde",
    "Liedekerke",
    "Lierde",
    "Lierre",
    "Lier",
    "Liers",
    "Ligny",
    "Lille Europe",
    "Lille Flandres",
    "Lillois",
    "Limal",
    "Limburg Süd",
    "Linkebeek",
    "Lissewege",
    "Liège-Carré",
    "Liège-Guillemins",
    "Liège-Saint-Lambert",
    "Lobbes",
    "Lodelinsart",
    "Lokeren",
    "Lommel",
    "Londerzeel",
    "Londres Saint Pancras",
    "London Saint Pancras International",
    "Londres-Waterloo",
    "London Waterloo",
    "Lonzée",
    "Lorraine TGV",
    "Lot",
    "Louvain",
    "Leuven",
    "Louvain-la-Neuve",
    "Lustin",
    "Luttre",
    "Luxembourg",
    "Lëtzebuerg",
    "Lyon Part Dieu TGV",
    "Lyon-Perrache TGV",
    "Lyon-Saint Exupéry TGV",
    "Maastricht",
    "Maastricht Randwyck",
    "Maffle",
    "Mainz Hbf",
    "Malderen",
    "Malines",
    "Mechelen",
    "Malines-Nekkerspoel",
    "Mechelen-Nekkerspoel",
    "Mamer",
    "Mamer-Lycée",
    "Manage",
    "Mannheim Hbf",
    "Marbehan",
    "Marche-en-Famenne",
    "Marche-les-Dames",
    "Marche-lez-Écaussinnes",
    "Marchienne-Zone",
    "Marchienne-au-Pont",
    "Maria-Aalter",
    "Mariembourg",
    "Marloie",
    "Marne-la-Vallée - Chessy",
    "Marseille-Saint-Charles",
    "Masnuy-Saint-Pierre",
    "Massy TGV",
    "Maubeuge",
    "Maubray",
    "Mazy",
    "Meer-Grens",
    "Meerssen",
    "Meiser",
    "Melkouwen",
    "Melle",
    "Melle PW",
    "Melreux-Hotton",
    "Melsele",
    "Menin",
    "Menen",
    "Merchtem",
    "Merelbeke",
    "Merode",
    "Mersch",
    "Messancy",
    "Metz",
    "Mevergnies-Attre",
    "Michelau",
    "Milmort",
    "Moensberg",
    "Mol",
    "Mollem",
    "Momalle",
    "Mons",
    "Mont-Saint-Guibert",
    "Montpellier",
    "Montpellier-Sud-de-France",
    "Moortsele",
    "Morlanwelz",
    "Mortsel",
    "Mortsel-Deurnesteenweg",
    "Mortsel-Liersesteenweg",
    "Mortsel-Oude God",
    "Mouscron",
    "Mouscron-Frontiere",
    "Moustier",
    "Moûtiers-Salins-Brides-les-Bai",
    "Muizen",
    "Mulhouse",
    "Munkzwalm",
    "Méry",
    "Namur",
    "Namêche",
    "Naninne",
    "Nantes",
    "Narbonne",
    "Natoye",
    "Neerpelt",
    "Neerwinden",
    "Nessonvaux",
    "Neufchâteau",
    "Neufvilles",
    "Nice Ville",
    "Niel",
    "Nieuwkerken-Waas",
    "Nijlen",
    "Nimy",
    "Ninove",
    "Nivelles",
    "Noorderkempen",
    "Nossegem",
    "Nîmes",
    "Obaix-Buzet",
    "Obourg",
    "Okegem",
    "Olen",
    "Oostkamp",
    "Opwijk",
    "Ostende",
    "Oostende",
    "Ottignies",
    "Oud-Heverlee",
    "Oudegem",
    "Ougrée",
    "Overpelt",
    "Paliseul",
    "Papignies",
    "Papegem",
    "Paris Nord",
    "Pepinster",
    "Pepinster-Cité",
    "Perpignan",
    "Petange",
    "Pfaffenthal-Kirchberg",
    "Philippeville",
    "Piéton",
    "Poix-Saint-Hubert",
    "Pont de Bois",
    "Pont-de-Seraing",
    "Pont-à-Celles",
    "Poperinge",
    "Poulseur",
    "Prague Gare centrale",
    "Praha Hlavní Nádraží",
    "Profondsart",
    "Pry",
    "Puurs",
    "Pécrot",
    "Péruwelz",
    "Quaregnon",
    "Quatrecht",
    "Kwatrecht",
    "Quevy",
    "Quevy-frontiere",
    "Quievrain",
    "Rebaix",
    "Remicourt",
    "Renaix",
    "Ronse",
    "Rennes",
    "Rhisnes",
    "Rhode-Saint-Genèse",
    "Sint-Genesius-Rode",
    "Rivage",
    "Rixensart",
    "Rochefort-Jemelle",
    "Rodange",
    "Ronet",
    "Roosendaal",
    "Rotterdam CS",
    "Roubaix",
    "Roulers",
    "Roeselare",
    "Roux",
    "Ruisbroek",
    "Ruisbroek-Sauvegarde",
    "Saint-Denis-Bovesse",
    "Saint-Ghislain",
    "Saint-Gilles-lez-Termonde",
    "Sint-Gillis-Dendermonde",
    "Saint-Job",
    "Sint-Job",
    "Saint-Louis-Haut-Rhin",
    "Saint-Nicolas",
    "Sint-Niklaas",
    "Saint-Raphaël-Valescure",
    "Saint-Trond",
    "Sint-Truiden",
    "Sart-Bernard",
    "Saverne",
    "Schaerbeek",
    "Schaarbeek/Schaerbeek",
    "Scheldewindeke",
    "Schelle",
    "Schellebelle",
    "Schendelbeke",
    "Schiphol",
    "Schoonaarde",
    "Schouweiler",
    "Schulen",
    "Sclaigneaux",
    "Sclessin",
    "Selestat",
    "Seraing",
    "Serskamp",
    "Siegburg",
    "Silly",
    "Simonis",
    "Sinaai",
    "Sint-Denijs-Boekel",
    "Sint-Joris-Weert",
    "Sint-Mariaburg",
    "Sleidinge",
    "Soignies",
    "Solre-sur-Sambre",
    "Spa",
    "Spa-Géronstère",
    "Statte",
    "Sterpenich-Frontiere",
    "Stockem",
    "Strasbourg",
    "Sy",
    "Sète",
    "Tamines",
    "Tamise",
    "Temse",
    "Terhagen",
    "Termonde",
    "Dendermonde",
    "Ternat",
    "Testelt",
    "Theux",
    "Thieu",
    "Thionville",
    "Thuin",
    "Thulin",
    "Tielen",
    "Tielt",
    "Tilff",
    "Tilly",
    "Tirlemont",
    "Tienen",
    "Tollembeek",
    "Tongres",
    "Tongeren",
    "Torhout",
    "Toulon",
    "Tour et Taxis",
    "Thurn en Taxis/Tour et Taxis",
    "Tourcoing",
    "Tournai",
    "Trois-Ponts",
    "Troisvierges",
    "Tronchiennes",
    "Drongen",
    "Trooz",
    "Tubize",
    "Turnhout",
    "Uccle-Calevoet",
    "Ukkel-Kalevoet/Uccle-Calevoet",
    "Uccle-Stalle",
    "Ukkel-Stalle/Uccle-Stalle",
    "Utrecht Centraal",
    "Valence TGV",
    "Valkenburg",
    "Veltem",
    "Venezia Santa Lucia",
    "Vertrijk",
    "Verviers-Central",
    "Verviers-Palais",
    "Viane-Moerbeke",
    "Vichte",
    "Vielsalm",
    "Vijfhuizen",
    "Ville-Pommerœul",
    "Villers-la-Ville",
    "Vilvorde",
    "Vilvoorde",
    "Virton",
    "Vise-Frontiere",
    "Visé",
    "Vivier d'Oie",
    "Diesdelle/Vivier d'Oie",
    "Viville",
    "Voroux",
    "Waarschoot",
    "Walcourt",
    "Waregem",
    "Waremme",
    "Waterloo",
    "Watermael",
    "Watermaal/Watermael",
    "Wavre",
    "Wavre-Sainte-Catherine",
    "Sint-Katelijne-Waver",
    "Weerde",
    "Welkenraedt",
    "Welle",
    "Wervik",
    "Wespelaar-Tildonk",
    "Wetteren",
    "Wevelgem",
    "Wezemaal",
    "Wichelen",
    "Wien Hbf",
    "Wijgmaal",
    "Wildert",
    "Willebroek",
    "Wilwerwiltz",
    "Wolfstee",
    "Wondelgem",
    "Y.renory",
    "Ypres",
    "Ieper",
    "Yves-Gomezée",
    "Yvoir",
    "Zandbergen",
    "Zaventem",
    "Zedelgem",
    "Zeebrugge-Dorp",
    "Zeebrugge-Strand",
    "Zele",
    "Zellik",
    "Zichem",
    "Zingem",
    "Zolder",
    "Zonhoven",
    "Zottegem",
    "Zwankendamme",
    "Zwijndrecht",
    "Zwijndrecht-Dorp",
    "Écaussinnes",
]

phrase_list_de: list[str] = [
    "'s Hertogenbosch",
    "Aachen Hbf",
    "Aachen West",
    "Aalst",
    "Aalst-Kerrebroek",
    "Aalter",
    "Aarschot",
    "Aarsele",
    "Acren",
    "Agde",
    "Aime-la-Plagne",
    "Aiseau",
    "Aix-en-Provence TGV",
    "Albertville",
    "Alken",
    "Almere Buiten",
    "Almere Centrum",
    "Amay",
    "Ampsin",
    "Amsterdam CS",
    "Amsterdam Centraal",
    "Amsterdam Zuid",
    "Andenne",
    "Anderlecht",
    "Angleur",
    "Annappes",
    "Ans",
    "Anseremme",
    "Antibes",
    "Antoing",
    "Antwerpen-Berchem",
    "Antwerpen-Centraal",
    "Antwerpen-Dam",
    "Antwerpen-Haven",
    "Antwerpen-Linkeroever",
    "Antwerpen-Luchtbal",
    "Antwerpen-Noorderdokken",
    "Antwerpen-Oost",
    "Antwerpen-Zuid",
    "Anzegem",
    "Appelterre",
    "Arcades",
    "Arcaden/Arcades",
    "Archennes",
    "Arel",
    "Arlon",
    "Arras",
    "Ascq",
    "Asse",
    "Assesse",
    "Ath",
    "Athem",
    "Athus",
    "Athus-Frontiere",
    "Aubange",
    "Aubange-Frontiere-Luxembourg",
    "Aulnoye-Aymeries",
    "Auvelais",
    "Avignon TGV",
    "Aye",
    "Aywaille",
    "Aéroport Charles-de-Gaulle TGV",
    "Baasrode-Zuid",
    "Baisieux",
    "Balegem-Dorp",
    "Balegem-Zuid",
    "Balen",
    "Bambrugge",
    "Barvaux",
    "Bas-Oha",
    "Bascharage-Sanem",
    "Basel",
    "Basse-Wavre",
    "Bastogne-Nord",
    "Bastogne-Sud",
    "Beauraing",
    "Beernem",
    "Beersel",
    "Beervelde",
    "Begijnendijk",
    "Beignée",
    "Bellem",
    "Belsele",
    "Beringen",
    "Berlaar",
    "Berlin HBF",
    "Berlin Lichtenberg",
    "Berlin Ostbahnhof",
    "Bertrange Strassen",
    "Bertrix",
    "Berzée",
    "Beuzet",
    "Beveren",
    "Beverlo",
    "Bierges-Walibi",
    "Bierset-Awans",
    "Bilzen",
    "Binche",
    "Bissegem",
    "Blandain-Frontiere",
    "Blankenberge",
    "Blanmont",
    "Blaton",
    "Bleret",
    "Bockstael",
    "Boechout",
    "Bokrijk",
    "Bomal",
    "Bonn-Beuel",
    "Booischot",
    "Boom",
    "Boondaal/Boondael",
    "Boortmeerbeek",
    "Bordeaux Saint Jean",
    "Bordet",
    "Bornem",
    "Bosvoorde/Boitsfort",
    "Bourg-Saint-Maurice",
    "Boussu",
    "Bouwel",
    "Bracquegnies",
    "Braine-l'Alleud",
    "Braine-le-Comte",
    "Breda",
    "Bressoux",
    "Brugelette",
    "Brugge",
    "Brugge-Sint-Pieters",
    "Brussel-Centraal/Bruxelles-Central",
    "Brussel-Congres/Bruxelles-Congrès",
    "Brussel-Kapellekerk/Bruxelles-Chapelle",
    "Brussel-Luxemburg/Bruxelles-Luxembourg",
    "Brussel-Noord/Bruxelles-Nord",
    "Brussel-Schuman/Bruxelles-Schuman",
    "Brussel-West/Bruxelles-Ouest",
    "Brussel-Zuid/Bruxelles-Midi",
    "Brussels Airport - Zaventem",
    "Buda",
    "Buggenhout",
    "Buizingen",
    "Burst",
    "Béziers",
    "Callenelle",
    "Cambron-Casteau",
    "Cannes",
    "Capellen",
    "Carlsbourg",
    "Carnieres",
    "Ceroux-Mousty",
    "Chambéry-Challes-les-Eaux",
    "Chapelle-Dieu",
    "Chapois",
    "Charleroi-Central",
    "Charleroi-Ouest",
    "Chastre",
    "Chaudfontaine",
    "Château-de-Seilles",
    "Châtelet",
    "Chênée",
    "Ciney",
    "Clervaux",
    "Colmar",
    "Comblain-la-Tour",
    "Comines / Komen",
    "Comines",
    "Coo",
    "Couillet",
    "Cour-sur-Heure",
    "Courcelles-Motte",
    "Courrière",
    "Court-Saint-Étienne",
    "Couvin",
    "Creil",
    "Croix Wasquehal",
    "Croix l'Allumette",
    "Dave-Saint-Martin",
    "De Hoek",
    "De Panne",
    "De Pinte",
    "Deinze",
    "Delta",
    "Den Haag HS",
    "Denderleeuw",
    "Dendermonde",
    "Diegem",
    "Diepenbeek",
    "Diesdelle/Vivier d'Oie",
    "Diest",
    "Diksmuide",
    "Dilbeek",
    "Dinant",
    "Dippach-Reckange",
    "Dolhain-Gileppe",
    "Dommeldange",
    "Dordrecht",
    "Dortmund Hbf",
    "Drauffelt",
    "Drongen",
    "Duesseldorf Flughafen (DE)",
    "Duffel",
    "Duinbergen",
    "Duisburg Hbf",
    "Düsseldorf Flughafen Hbf",
    "Düsseldorf Hbf",
    "Duesseldorf Hbf",
    "Ebbsfleet International",
    "Ede",
    "Eeklo",
    "Eichem",
    "Eijsden",
    "Eine",
    "Eke-Nazareth",
    "Ekeren",
    "Enghien / Edingen",
    "Enghien",
    "Engis",
    "Eppegem",
    "Erbisoeul",
    "Erbisœul",
    "Erembodegem",
    "Ernage",
    "Erpe-Mere",
    "Erps-Kwerps",
    "Erquelinnes",
    "Erquelinnes-Frontière",
    "Erquelinnes-Village",
    "Esneux",
    "Essen",
    "Essen Hbf",
    "Essen-Grens",
    "Essene-Lombeek",
    "Ettelbrück",
    "Ettelbréck",
    "Etterbeek",
    "Eupen",
    "Evere",
    "Evergem",
    "Eygelshoven markt",
    "Ezemaal",
    "Familleureux",
    "Farciennes",
    "Faux",
    "Fexhe-le-Haut-Clocher",
    "Flawinne",
    "Flemalle-Grande",
    "Flemalle-Haute",
    "Fleurus",
    "Floreffe",
    "Florenville",
    "Florival",
    "Florée",
    "Fontaine-Valmont",
    "Forchies",
    "Forrières",
    "Fraipont",
    "Frameries",
    "Franchimont",
    "Franière",
    "Frankfurt am Main Flughafen Fernbf",
    "Frankfurt am Main Flughafen Reginalbf",
    "Frankfurt am Main Hbf",
    "Froyennes",
    "Galmaarden",
    "Gastuche",
    "Gavere-Asper",
    "Gedinne",
    "Geel",
    "Gembloux",
    "Gendron-Celles",
    "Genk",
    "Genly",
    "Gent-Dampoort",
    "Gent-Sint-Pieters",
    "Gentbrugge",
    "Genval",
    "Geraardsbergen",
    "Germoir",
    "Mouterij/Germoir",
    "Ghlin",
    "Glons",
    "Godarville",
    "Godinne",
    "Goebelsmühle",
    "Gontrode",
    "Gouvy",
    "Gouvy-Frontiere",
    "Gouy-lez-Pieton",
    "Graide",
    "Groenendaal",
    "Groot-Bijgaarden",
    "Grupont",
    "Haacht",
    "Haaltert",
    "Habay",
    "Hainin",
    "Halanzy",
    "Halle",
    "Ham-sur-Heure",
    "Ham-sur-Sambre",
    "Hambos",
    "Hamoir",
    "Hamont",
    "Hansbeke",
    "Harchies",
    "Harelbeke",
    "Haren",
    "Haren-Sud/Haren-Zuid",
    "Hasselt",
    "Haute-Flône",
    "Haute-Picardie TGV",
    "Haversin",
    "Havre",
    "Heerlen",
    "Heide",
    "Heist",
    "Heist-op-den-Berg",
    "Heizijde",
    "Hellemmes",
    "Hemiksem",
    "Hennuyères",
    "Herent",
    "Herentals",
    "Hergenrath",
    "Hergenrath-Frontiere",
    "Herne",
    "Herseaux",
    "Herstal",
    "Herzele",
    "Herzogenrath",
    "Heusden",
    "Hever",
    "Heverlee",
    "Hillegem",
    "Hoboken-Polder",
    "Hoeilaart",
    "Hofstade",
    "Holleken",
    "Hollerich",
    "Hony",
    "Houraing",
    "Hourpes",
    "Houyet",
    "Hove",
    "Huizingen",
    "Huy",
    "Idar-Oberstein",
    "Iddergem",
    "Idegem",
    "Ieper",
    "Ingelmunster",
    "Izegem",
    "Jambes",
    "Jambes-Est",
    "Jamioulx",
    "Jemappes",
    "Jemeppe-sur-Meuse",
    "Jemeppe-sur-Sambre",
    "Jette",
    "Jurbise",
    "Jurbeke",
    "Juslenville",
    "Kalmthout",
    "Kapelle-op-den-Bos",
    "Kapellen",
    "Kautenbach",
    "Kautebaach",
    "Kessel",
    "Kiewit",
    "Kijkuit",
    "Kleinbettingen",
    "Klengbetten",
    "Knokke",
    "Koblenz Hbf",
    "Koksijde",
    "Kontich-Lint",
    "Kortemark",
    "Kortenberg",
    "Kortrijk",
    "Kwatrecht",
    "Köln Hbf",
    "La Hulpe",
    "La Louvière-Centre",
    "La Louvière-Sud",
    "La Roche (Brabant)",
    "Labuissière",
    "Lamadeleine",
    "Landegem",
    "Landelies",
    "Landen",
    "Landgraaf",
    "Landry",
    "Landskouter",
    "Langdorp",
    "Le Campinaire",
    "Lebbeke",
    "Lede",
    "Leignon",
    "Lelystad Centrum",
    "Leman",
    "Lembeek",
    "Lens",
    "Leopoldsburg",
    "Les Arcs - Draguignan",
    "Lessines",
    "Lessen",
    "Leudelange",
    "Leuze",
    "Leval",
    "Lezennes",
    "Libramont",
    "Lichtervelde",
    "Liedekerke",
    "Lier",
    "Lierde",
    "Liers",
    "Ligny",
    "Lille Europe",
    "Lille Flandres",
    "Lillois",
    "Limal",
    "Limburg Süd",
    "Linkebeek",
    "Lissewege",
    "Liège-Carré",
    "Liège-Guillemins",
    "Liège-Saint-Lambert",
    "Lobbes",
    "Lodelinsart",
    "Lokeren",
    "Lommel",
    "Londerzeel",
    "London Saint Pancras International",
    "London Waterloo",
    "Lonzée",
    "Lorraine TGV",
    "Lot",
    "Louvain-la-Neuve",
    "Lustin",
    "Luttre",
    "Luxemburg",
    "Lëtzebuerg",
    "Lyon Part Dieu TGV",
    "Lyon-Perrache TGV",
    "Lyon-Saint Exupéry TGV",
    "Löwen",
    "Leuven",
    "Maastricht",
    "Maastricht Randwyck",
    "Maffle",
    "Mainz Hbf",
    "Malderen",
    "Mamer",
    "Mamer-Lycée",
    "Manage",
    "Mannheim Hbf",
    "Marbehan",
    "Marche-en-Famenne",
    "Marche-les-Dames",
    "Marche-lez-Écaussinnes",
    "Marchienne-Zone",
    "Marchienne-au-Pont",
    "Maria-Aalter",
    "Mariembourg",
    "Marloie",
    "Marne-la-Vallée - Chessy",
    "Marseille-Saint-Charles",
    "Masnuy-Saint-Pierre",
    "Massy TGV",
    "Maubeuge",
    "Maubray",
    "Mazy",
    "Mechelen",
    "Mechelen-Nekkerspoel",
    "Meer-Grens",
    "Meerssen",
    "Meiser",
    "Melkouwen",
    "Melle",
    "Melle PW",
    "Melreux-Hotton",
    "Melsele",
    "Menen",
    "Merchtem",
    "Merelbeke",
    "Merode",
    "Mersch",
    "Messancy",
    "Metz",
    "Mevergnies-Attre",
    "Michelau",
    "Milmort",
    "Moensberg",
    "Mol",
    "Mollem",
    "Momalle",
    "Mons",
    "Mont-Saint-Guibert",
    "Montpellier",
    "Montpellier-Sud-de-France",
    "Moortsele",
    "Morlanwelz",
    "Mortsel",
    "Mortsel-Deurnesteenweg",
    "Mortsel-Liersesteenweg",
    "Mortsel-Oude God",
    "Mouscron / Moeskroen",
    "Mouscron",
    "Mouscron-Frontiere",
    "Moustier",
    "Moûtiers-Salins-Brides-les-Bai",
    "Muizen",
    "Mulhouse",
    "Munkzwalm",
    "Méry",
    "Namur",
    "Namêche",
    "Naninne",
    "Nantes",
    "Narbonne",
    "Natoye",
    "Neerpelt",
    "Neerwinden",
    "Nessonvaux",
    "Neufchâteau",
    "Neufvilles",
    "Nice Ville",
    "Niel",
    "Nieuwkerken-Waas",
    "Nijlen",
    "Nimy",
    "Ninove",
    "Nivelles",
    "Noorderkempen",
    "Nossegem",
    "Nîmes",
    "Obaix-Buzet",
    "Obourg",
    "Okegem",
    "Olen",
    "Oostende",
    "Oostkamp",
    "Opwijk",
    "Ottignies",
    "Oud-Heverlee",
    "Oudegem",
    "Oudenaarde",
    "Ougrée",
    "Overpelt",
    "Paliseul",
    "Papignies",
    "Papegem",
    "Paris Nord",
    "Pepinster",
    "Pepinster-Cité",
    "Perpignan",
    "Petange",
    "Pfaffenthal-Kirchberg",
    "Philippeville",
    "Piéton",
    "Poix-Saint-Hubert",
    "Pont de Bois",
    "Pont-de-Seraing",
    "Pont-à-Celles",
    "Poperinge",
    "Poulseur",
    "Prag Hauptbahnhof",
    "Praha Hlavní Nádraží",
    "Profondsart",
    "Pry",
    "Puurs",
    "Pécrot",
    "Péruwelz",
    "Quaregnon",
    "Quevy",
    "Quevy-frontiere",
    "Quievrain",
    "Rebaix",
    "Remicourt",
    "Renaix / Ronse",
    "Ronse",
    "Rennes",
    "Rhisnes",
    "Rhode-St.-Genese/st.-Genesius-Rode",
    "Sint-Genesius-Rode",
    "Rivage",
    "Rixensart",
    "Rochefort-Jemelle",
    "Rodange",
    "Roeselare",
    "Ronet",
    "Roosendaal",
    "Rotterdam CS",
    "Roubaix",
    "Roux",
    "Ruisbroek",
    "Ruisbroek-Sauvegarde",
    "Saint-Denis-Bovesse",
    "Saint-Ghislain",
    "Saint-Job / Sint-Job",
    "Sint-Job",
    "Saint-Louis-Haut-Rhin",
    "Saint-Raphaël-Valescure",
    "Sart-Bernard",
    "Saverne",
    "Schaarbeek/Schaerbeek",
    "Scheldewindeke",
    "Schelle",
    "Schellebelle",
    "Schendelbeke",
    "Schiphol",
    "Schoonaarde",
    "Schouweiler",
    "Schulen",
    "Sclaigneaux",
    "Sclessin",
    "Selestat",
    "Seraing",
    "Serskamp",
    "Siegburg",
    "Silly",
    "Simonis",
    "Sinaai",
    "Sint-Agatha-Berchem/Berchem-Sainte-Agathe",
    "Sint-Denijs-Boekel",
    "Sint-Gillis",
    "Sint-Gillis-Dendermonde",
    "Sint-Joris-Weert",
    "Sint-Katelijne-Waver",
    "Sint-Mariaburg",
    "Sint-Martens-Bodegem",
    "Sint-Niklaas",
    "Sint-Truiden",
    "Sleidinge",
    "Soignies",
    "Solre-sur-Sambre",
    "Spa",
    "Spa-Géronstère",
    "Statte",
    "Sterpenich-Frontiere",
    "Stockem",
    "Straßburg",
    "Strasbourg",
    "Sy",
    "Sète",
    "Tamines",
    "Temse",
    "Terhagen",
    "Ternat",
    "Testelt",
    "Theux",
    "Thienen",
    "Tienen",
    "Thieu",
    "Thionville",
    "Thuin",
    "Thulin",
    "Tielen",
    "Tielt",
    "Tilff",
    "Tilly",
    "Tollembeek",
    "Tongern",
    "Tongeren",
    "Torhout",
    "Toulon",
    "Tour et Taxis",
    "Thurn en Taxis/Tour et Taxis",
    "Tourcoing",
    "Tournai",
    "Trois-Ponts",
    "Troisvierges",
    "Trooz",
    "Tubize",
    "Turnhout",
    "Ukkel-Kalevoet/Uccle-Calevoet",
    "Ukkel-Stalle/Uccle-Stalle",
    "Utrecht Centraal",
    "Valence TGV",
    "Valkenburg",
    "Veltem",
    "Venezia Santa Lucia",
    "Vertrijk",
    "Verviers-Central",
    "Verviers-Palais",
    "Veurne",
    "Viane-Moerbeke",
    "Vichte",
    "Vielsalm",
    "Vijfhuizen",
    "Ville-Pommerœul",
    "Villers-la-Ville",
    "Vilvoorde",
    "Virton",
    "Vise-Frontiere",
    "Visé",
    "Viville",
    "Voroux",
    "Vorst-Oost/Forest-Est",
    "Vorst-Zuid/Forest-Midi",
    "Waarschoot",
    "Walcourt",
    "Waregem",
    "Waremme",
    "Waterloo",
    "Watermaal/Watermael",
    "Wavre",
    "Weerde",
    "Welkenraedt",
    "Welle",
    "Wervik",
    "Wespelaar-Tildonk",
    "Wetteren",
    "Wevelgem",
    "Wezemaal",
    "Wichelen",
    "Wien Hbf",
    "Wijgmaal",
    "Wildert",
    "Willebroek",
    "Wilwerwiltz",
    "Wolfstee",
    "Wondelgem",
    "Y.renory",
    "Yves-Gomezée",
    "Yvoir",
    "Zandbergen",
    "Zaventem",
    "Zedelgem",
    "Zeebrugge-Dorp",
    "Zeebrugge-Strand",
    "Zele",
    "Zellik",
    "Zichem",
    "Zingem",
    "Zolder",
    "Zonhoven",
    "Zottegem",
    "Zwankendamme",
    "Zwijndrecht",
    "Zwijndrecht-Dorp",
    "Écaussinnes",
]

_PHRASE_LISTS_BY_LANGUAGE: Final[dict[str, list[str]]] = {
    "en": phrase_list_en,
    "nl": phrase_list_nl,
    "fr": phrase_list_fr,
    "de": phrase_list_de,
}

_LANGUAGE_ALIASES: Final[dict[str, str]] = {
    "en": "en",
    "en-us": "en",
    "en-gb": "en",
    "english": "en",
    "nl": "nl",
    "nl-be": "nl",
    "nl-nl": "nl",
    "dutch": "nl",
    "flemish": "nl",
    "vlaams": "nl",
    "fr": "fr",
    "fr-be": "fr",
    "fr-fr": "fr",
    "french": "fr",
    "de": "de",
    "de-be": "de",
    "de-de": "de",
    "german": "de",
}


def normalize_phrase_list_language(language_or_locale: str) -> str:
    """Return the phrase-list language key for a language name or BCP-47 locale."""
    key = language_or_locale.strip().lower().replace("_", "-")
    try:
        return _LANGUAGE_ALIASES[key]
    except KeyError as exc:
        supported = ", ".join(sorted(_LANGUAGE_ALIASES))
        raise ValueError(
            f"Unsupported phrase-list language {language_or_locale!r}. Supported: {supported}"
        ) from exc


def get_phrase_list(language_or_locale: str) -> list[str]:
    """Return a copy of the station phrase list for a language or locale."""
    language = normalize_phrase_list_language(language_or_locale)
    return list(_PHRASE_LISTS_BY_LANGUAGE[language])


def get_phrase_lists_by_language() -> dict[str, list[str]]:
    """Return copies of all station phrase lists keyed by iRail language code."""
    return {
        language: list(phrases)
        for language, phrases in _PHRASE_LISTS_BY_LANGUAGE.items()
    }


__all__ = [
    "phrase_list_en",
    "phrase_list_nl",
    "phrase_list_fr",
    "phrase_list_de",
    "get_phrase_list",
    "get_phrase_lists_by_language",
    "normalize_phrase_list_language",
]
